/*DROP DATABASE IF EXISTS PRODUCTS;
CREATE DATABASE PRODUCTS;*/
USE PRODUCTS;

/*DROP TABLE IF EXISTS PAQUETE;
CREATE TABLE PAQUETE(
	CODE			VARCHAR(8)		NOT NULL	PRIMARY KEY,
	IMG				VARCHAR(3000)	NOT NULL,
	NAME			VARCHAR(80)		NOT NULL,
	DESCRIPTION		VARCHAR(3000)	NOT NULL,
	COST			FLOAT			NOT NULL,
	LINK			VARCHAR(3000)	NOT NULL
);*/
/*DROP TABLE IF EXISTS LUGARES;
CREATE TABLE LUGARES(
	CODE			VARCHAR(5)		PRIMARY KEY,
	CONTINENTE		VARCHAR(50),
	PAIS			VARCHAR(50),
	LUGTUR			VARCHAR(50)
);*/
DROP TABLE IF EXISTS ADMINISTRADOR;
CREATE TABLE ADMINISTRADOR(
	EMAIL			VARCHAR(40)		NOT NULL	PRIMARY KEY,
	PASSW			VARCHAR(30)		NOT NULL
);
/*DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO(
	USERCODE		SMALLINT		NOT NULL	PRIMARY KEY		IDENTITY(1000,1),
	EMAIL			VARCHAR(40)		NOT NULL,
	NOMBRE			VARCHAR(100)	NOT NULL,
	PASSW			VARCHAR(30)		NOT NULL
);*/
/*DROP TABLE IF EXISTS COMENTARIO;
CREATE TABLE COMENTARIO(
	CODCOM			SMALLINT		NOT NULL	PRIMARY KEY					IDENTITY(1000,1),
	CODPACK			VARCHAR(8)		NOT NULL	REFERENCES PAQUETE(CODE)	ON DELETE CASCADE,
	NOMUS			VARCHAR(100)	NOT NULL,
	COMENT			VARCHAR(5000)	NOT NULL,
	DATECOM			VARCHAR(10)		NOT NULL,
	CODANSWER		SMALLINT		NOT NULL,
	VOTO			TINYINT			NOT NULL
);*/
/*DROP TABLE IF EXISTS VOTOS;
CREATE TABLE VOTOS(
	CODCOMENT		SMALLINT		NOT NULL	REFERENCES COMENTARIO(CODCOM)	ON DELETE CASCADE,
	CODUS			SMALLINT		NOT NULL	REFERENCES USUARIO(USERCODE)	ON DELETE CASCADE,
	VOTE			TINYINT			NOT NULL
);*/


/*INSERT INTO ADMINISTRADOR VALUES ('expectra2010@gmail.com','admin123');
INSERT INTO USUARIO (EMAIL, NOMBRE, PASSW) VALUES ('expectra2010@hotmail.com','Gustavo Adolfo Ugaz Cárdenas','user123');
INSERT INTO USUARIO (EMAIL, NOMBRE, PASSW) VALUES ('sasuke@hotmail.com','Mijailobitch Freddy Montes Meza','sasuke123');*/
/*SELECT IDENT_CURRENT('USUARIO') AS 'USER_LAST_ID';*/
/*INSERT INTO COMENTARIO (NOMUS,COMENT,DATECOM,CODANSWER,VOTE) VALUES	('CARLA','PAN','06/10/2021',1003,0);*/

SELECT * FROM VOTOS;
SELECT * FROM COMENTARIO;
SELECT * FROM ADMINISTRADOR;
SELECT * FROM USUARIO;
SELECT * FROM LUGARES;
SELECT * FROM PAQUETE;
/*SELECT DISTINCT PAIS FROM LUGARES WHERE CONTINENTE='america_sur';*/
/*SELECT LUGTUR FROM LUGARES WHERE PAIS='peru';*/
/*SELECT CODE FROM LUGARES WHERE CONTINENTE = 'america_central';*/
/*SELECT * FROM PAQUETE WHERE SUBSTRING(CODE, 2, 5) = '70715';*/